export default {
  index: 'Introduction',
  '-- Overview': {
    type: 'separator',
    title: 'Overview',
  },
  'architecture': 'Architecture',
  'tech-stack': 'Tech Stack',
  'setup': 'Setup & Deployment',
  'env-vars': 'Environment Variables',
  '-- Core Systems': {
    type: 'separator',
    title: 'Core Systems',
  },
  'claude-integration': 'Claude Integration',
  'tools': 'Tools Reference',
  'trading': 'Trading Engine',
  'wallets': 'Wallets',
  'background-jobs': 'Background Jobs',
  'deposit-notifications': 'Deposit Notifications',
  'error-handling': 'Error Handling',
  '-- Features': {
    type: 'separator',
    title: 'Features',
  },
  'premium': 'Premium Model',
  'alpha-callers': 'Alpha Callers',
  'auto-sell': 'Auto-Sell',
  'monitors': 'Monitors System',
  'account-recovery': 'Account Recovery',
  '-- Dashboards': {
    type: 'separator',
    title: 'Dashboards',
  },
  'analytics': 'Public Analytics',
  'admin-dashboard': 'Admin Dashboard',
  '-- Security & Infra': {
    type: 'separator',
    title: 'Security & Infra',
  },
  'safety': 'Safety & Security',
  'agent-identity': 'Agent Identity (ERC-8004)',
  'database': 'Database',
  'ci-cd': 'CI/CD Pipeline',
}
